version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bot_database
    restart: always
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: bot_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: telegram_bot
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://bot_user:bot_password@db:5432/bot_db"
      TELEGRAM_TOKEN: "YOUR_TOKEN"

volumes:
  db-data: